
SELECT * FROM REQUISICIONESDT

SELECT * FROM REQUISICIONES
SELECT * FROM ITEMSREQ




SELECT MIN(REQUISICIONES.ID) AS ID,  MIN(REQUISICIONES.CNSREQ) AS CNSREQ, REQUISICIONES.CARGO, REQUISICIONES.SOLICITANTE ,REQUISICIONES.CEDULA,MIN(CONVERT(VARCHAR(30),REQUISICIONES.FECHA_SOLICITUD,20)) AS FECHA_INICIAL_SOLICITUD,
 ITEMSREQ.ITEM,
   ITEMSREQ.CANTIDAD
       FROM REQUISICIONES
          INNER JOIN ITEMSREQ
      ON ITEMSREQ.CEDULA = REQUISICIONES.CEDULA 
          WHERE ITEMSREQ.CEDULA = REQUISICIONES.CEDULA 
    AND REQUISICIONES.CARGO = ITEMSREQ.CARGO
  AND  ITEMSREQ.IDREQ IS NULL  AND ITEMSREQ.CNSREQ IS NULL
 GROUP BY ITEMSREQ.ITEM,ITEMSREQ.CANTIDAD,REQUISICIONES.CEDULA,REQUISICIONES.CARGO,REQUISICIONES.SOLICITANTE
 HAVING MIN(CONVERT(VARCHAR(30),ITEMSREQ.FECHA_SOLICITUD,20)) = MIN(CONVERT(VARCHAR(30),REQUISICIONES.FECHA_SOLICITUD,20))





SELECT MIN(REQUISICIONES.ID) AS ID,  MIN(REQUISICIONES.CNSREQ) AS CNSREQ, REQUISICIONES.CARGO, REQUISICIONES.SOLICITANTE ,REQUISICIONES.CEDULA,MIN(CONVERT(VARCHAR(30),REQUISICIONES.FECHA_SOLICITUD,20)) AS FECHA_INICIAL_SOLICITUD,
 ITEMSREQ.ITEM,
   ITEMSREQ.CANTIDAD
       FROM REQUISICIONES
          INNER JOIN ITEMSREQ
      ON ITEMSREQ.CEDULA = REQUISICIONES.CEDULA AND REQUISICIONES.CARGO = ITEMSREQ.CARGO 
          WHERE ITEMSREQ.CEDULA = REQUISICIONES.CEDULA 
    AND REQUISICIONES.CARGO = ITEMSREQ.CARGO
  AND  ITEMSREQ.IDREQ IS NULL  AND ITEMSREQ.CNSREQ IS NULL
 GROUP BY ITEMSREQ.ITEM,ITEMSREQ.CANTIDAD,REQUISICIONES.CEDULA,REQUISICIONES.CARGO,REQUISICIONES.SOLICITANTE
 HAVING MIN(CONVERT(VARCHAR(30),ITEMSREQ.FECHA_SOLICITUD,20)) = MIN(CONVERT(VARCHAR(30),REQUISICIONES.FECHA_SOLICITUD,20))




SELECT ITEMSREQ.ITEM, ITEMSREQ.CANTIDAD FROM REQUISICIONES INNER JOIN ITEMSREQ  ON ITEMSREQ.CEDULA = REQUISICIONES.CEDULA WHERE ITEMSREQ.CEDULA = REQUISICIONES.CEDULA AND REQUISICIONES.CARGO = ITEMSREQ.CARGO AND  ITEMSREQ.IDREQ IS NULL  AND ITEMSREQ.CNSREQ IS NULL AND REQUISICIONES.CNSREQ='CNSREQ1' AND REQUISICIONES.ID='1' GROUP BY ITEMSREQ.ITEM,ITEMSREQ.CANTIDAD,REQUISICIONES.CEDULA,REQUISICIONES.CARGO,REQUISICIONES.SOLICITANTE HAVING MIN(CONVERT(VARCHAR(30),ITEMSREQ.FECHA_SOLICITUD,20)) = MIN(CONVERT(VARCHAR(30),REQUISICIONES.FECHA_SOLICITUD,20))
