SELECT 
       ITEMSREQ.CNSITEMREQ AS 'ITEM_CONSECUTIVO',
       ITEMSREQ.ITEM AS ITEM,
       ITEMSREQ.CANTIDAD AS CANTIDAD,
	   (CASE  WHEN ITEMSREQ.ITEMAPROBADO=1 THEN 'APROBADO'
	          WHEN ITEMSREQ.ITEMAPROBADO=0 THEN 'NO APROBADO'
		END) AS ITEMS,
		(CASE 
			  WHEN ITEMSREQ.ITEMAPROBADO = 0 
			  THEN CASE WHEN ITEMSREQ.RECIBIDO IS NULL  THEN 'ITEM NO APROBADO PARA ENTREGA' END
			  WHEN ITEMSREQ.ITEMAPROBADO = 1 
			  THEN CASE WHEN ITEMSREQ.RECIBIDO IS NULL THEN 'ITEM AUN NO RECIBIDO' 
			            WHEN ITEMSREQ.RECIBIDO=1 THEN 'RECIBIDO' 
					    WHEN ITEMSREQ.RECIBIDO=0 THEN 'NO RECIBIDO' 
					   END
			  END)
			  AS RECIBIDO
 FROM ITEMSREQ
 INNER JOIN REQUISICIONES ON
 ITEMSREQ.CNSREQ = REQUISICIONES.CNSREQ



