SELECT (CASE WHEN FECHA_ENTREGA IS NOT NULL THEN FECHA_ENTREGA ELSE 'SIN FIRMA'  END) AS FECHA_ENTREGA
FROM REQUISICIONES
WHERE CNSREQ='CNSREQ1'


SELECT (CASE WHEN ESTADO_ITEMS IS NOT NULL THEN ESTADO_ITEMS ELSE -1  END) AS ESTADO_ITEMS FROM REQUISICIONES