SELECT ITEMSREQ.ITEM AS ITEM, ITEMSREQ.CANTIDAD AS CANTIDAD ,ITEMSREQ.ID AS ID   
FROM ITEMSREQ INNER JOIN REQUISICIONES  ON ITEMSREQ.CEDULA = REQUISICIONES.CEDULA   
WHERE ITEMSREQ.CEDULA = REQUISICIONES.CEDULA AND REQUISICIONES.CARGO = ITEMSREQ.CARGO  
AND  ITEMSREQ.IDREQ IS NULL  AND ITEMSREQ.CNSREQ IS NULL AND REQUISICIONES.CNSREQ='CNSREQ5'  
AND REQUISICIONES.ID=5  OR ITEMSREQ.IDREQ IS NOT NULL  AND ITEMSREQ.CNSREQ IS NOT NULL AND REQUISICIONES.CNSREQ='CNSREQ5'  
AND REQUISICIONES.ID=5
GROUP BY ITEMSREQ.ITEM,ITEMSREQ.CANTIDAD,REQUISICIONES.CEDULA,ITEMSREQ.ID,  
REQUISICIONES.CARGO,REQUISICIONES.SOLICITANTE , REQUISICIONES.FECHA_SOLICITUD, ITEMSREQ.FECHA_SOLICITUD   
HAVING  CONVERT(varchar(16),REQUISICIONES.FECHA_SOLICITUD,20) = CONVERT(varchar(16),ITEMSREQ.FECHA_SOLICITUD,20) ORDER BY 3 ASC