  SELECT     
	   	   				 MIDATA.[CONSECUTIVO REQUISICION] AS 'CONSECUTIVO REQUISICION',MIDATA.SOLICITANTE AS 'SOLICITANTE', MIDATA.AREA AS 'AREA', MIDATA.CARGO AS 'CARGO', MIDATA.CENTRO_OPERACION AS CENTRO_OPERACION , MIDATA.[FECHA DE SOLICITUD] AS FECHA_SOLICITUD , MIDATA.[FECHA DE APROBACION] AS FECHA_APROBACION, MIDATA.[ITEM APROBADO] AS ITEMS_APROBADOS, COALESCE(MIDATA.[ITEM NO APROBADO],0) AS 'ITEMS NO APROBADOS',    
	   	   				 (CASE WHEN COALESCE(MIDATA.[FECHA DE ENTREGA],'SIN FECHA')= 'SIN FECHA' THEN 'FECHA DE ENTREGA AUN NO ASIGNADA'   
	   	   				 WHEN COALESCE(MIDATA.[FECHA DE ENTREGA],'SIN FECHA')<> 'SIN FECHA'  THEN 'FECHA DE ENTREGA ASIGNADA'   
	   	   				 END) AS FECHA_ENTREGA ,    
	   	   				 (CASE                        WHEN  MIDATA.[ESTADO DE ITEMS]  IS NULL  THEN  'REQUISICION POR ENTREGAR'   
	   	   		     	                               WHEN  MIDATA.[ESTADO DE ITEMS] =2 THEN 'REQUISICION RECIBIDA'   
	   	   				                               WHEN  MIDATA.[ESTADO DE ITEMS]=1 THEN 'REQUISICION TRAMITADA'   
	   	   				 							  WHEN  MIDATA.[ESTADO DE ITEMS] =0 THEN 'REQUISICION EN PROCESO'   
	   	   		     	 							  WHEN  MIDATA.[ESTADO DE ITEMS] =3 THEN 'REQUISICION CERRADA'   
	   	   				 END) AS ESTADO_ITEMS   
	   	   				  FROM  (SELECT * FROM (SELECT    
	   	   				 REQUISICIONES.CNSREQ AS 'CONSECUTIVO REQUISICION',    
	   	   				 REQUISICIONES.SOLICITANTE AS 'SOLICITANTE',   
	   	   				 REQUISICIONES.AREA AS 'AREA',   
	   	   				 REQUISICIONES.CARGO AS 'CARGO',   
	   	   			     REQUISICIONES.CENTRO_OPERACION AS 'CENTRO_OPERACION',   
	   	   				 REQUISICIONES.FECHA_ENTREGA AS 'FECHA DE ENTREGA' ,   
	   	   				 REQUISICIONES.ESTADO_ITEMS AS 'ESTADO DE ITEMS',   
	   	   				 CONVERT(VARCHAR(16),REQUISICIONES.FECHA_SOLICITUD,20) AS 'FECHA DE SOLICITUD',   
	   	   				 CONVERT(VARCHAR(16),REQUISICIONESDT.FECHA_DE_FIRMA,20) AS 'FECHA DE APROBACION',   
	   	   				 COUNT(ITEMSREQ.ITEM) AS CANTIDAD,   
	   	   				 (CASE WHEN ITEMSREQ.ITEMAPROBADO=1 THEN  'ITEM APROBADO'   
	   	   				       WHEN ITEMSREQ.ITEMAPROBADO=0 THEN 'ITEM NO APROBADO' END) AS ESTADO   
	   	   				        FROM REQUISICIONES   
	   	   				 	   INNER JOIN ITEMSREQ ON   
	   	   				 	   ITEMSREQ.CNSREQ = REQUISICIONES.CNSREQ   
	   	   				 	   INNER JOIN REQUISICIONESDT ON   
	   	   				 	   REQUISICIONESDT.CNSREQ = REQUISICIONES.CNSREQ   
	   	   				 	   WHERE REQUISICIONES.APROBACION=1 AND ITEMSREQ.ITEMAPROBADO = 1 AND  REQUISICIONES.APROBACION=1 OR ITEMSREQ.ITEMAPROBADO = 0   
	   	   				 	   GROUP BY REQUISICIONES.CNSREQ,REQUISICIONES.SOLICITANTE,REQUISICIONES.CARGO,REQUISICIONES.CENTRO_OPERACION,REQUISICIONES.FECHA_SOLICITUD,   
	   	   				 	   REQUISICIONESDT.FECHA_DE_FIRMA,ITEMSREQ.ITEMAPROBADO,REQUISICIONES.AREA,REQUISICIONES.FECHA_ENTREGA,REQUISICIONES.ESTADO_ITEMS   
	   	   				 	   ) AS T   
	   	   				 	    PIVOT   
	   	   				 	   (   
	   	   				 	   SUM (CANTIDAD)     
	   	   				        FOR ESTADO IN     
	   	   				        (  [ITEM APROBADO],[ITEM NO APROBADO] )     
	   	   				        )  AS PIVOTTABLE)MIDATA   
	   	   				 	  ORDER BY CONVERT(VARCHAR(16),MIDATA.[FECHA DE SOLICITUD],20) ASC ;