SELECT CONVERT (VARCHAR(30),
(CASE WHEN REQUISICIONESDT.APROBACION=1 THEN 'REQUISICION APROBADA' ELSE 'AUN SIN APROBACION' END) ) AS ESTADO,
SOLICITANTE, AREA, CARGO, CENTRO_OPERACION, FECHA_SOLICITUD,  CNSREQ FROM REQUISICIONESDT