CREATE PROCEDURE INSERTAFINALDATACOPY
AS

DECLARE 

@SOLICITANTE VARCHAR(30),
@CONSECUTIVO VARCHAR(30),
@AREA VARCHAR(30) , 
@CARGO VARCHAR(50) ,
@CENTRO_OPERACION VARCHAR(50),
@FECHA_SOLICITUD DATETIME,
@CANTIDAD INT, 
@ITEM VARCHAR(30),
@INID VARCHAR(30)


DECLARE INSERTFINALCOPYDATA CURSOR

FOR


  SELECT REQUISICIONES.SOLICITANTE AS SOLICITANTE, 
  REQUISICIONES.CNSREQ AS CONSECUTIVO, REQUISICIONES.AREA AS AREA, REQUISICIONES.CARGO AS CARGO,
  REQUISICIONES.CENTRO_OPERACION AS CENTRO_OPERACION,
  REQUISICIONES.FECHA_SOLICITUD AS FECHA_SOLICITUD, CANTIDAD AS CANTIDAD, ITEM AS ITEM
  FROM REQUISICIONES 
  INNER JOIN ITEMSREQ 
  ON ITEMSREQ.CEDULA = REQUISICIONES.CEDULA AND ITEMSREQ.CARGO = REQUISICIONES.CARGO   
  WHERE REQUISICIONES.REVISION IS NULL AND REQUISICIONES.APROBACION IS NULL
  AND REQUISICIONES.FIRMA_REVISION IS NULL AND  REQUISICIONES.CNSREQ NOT IN 
  (SELECT CONSECUTIVO  FROM RQITEMSTEMPORAL) 
  GROUP BY
  REQUISICIONES.CARGO, REQUISICIONES.CENTRO_OPERACION, REQUISICIONES.CEDULA,   
  ITEMSREQ.CANTIDAD,  ITEMSREQ.ITEM , REQUISICIONES.CNSREQ, REQUISICIONES.SOLICITANTE, REQUISICIONES.FECHA_SOLICITUD, ITEMSREQ.FECHA_SOLICITUD,  REQUISICIONES.AREA  
  HAVING CONVERT(VARCHAR(16),ITEMSREQ.FECHA_SOLICITUD,20) = CONVERT(VARCHAR(16),REQUISICIONES.FECHA_SOLICITUD,20)


  OPEN INSERTFINALCOPYDATA

      FETCH NEXT FROM INSERTFINALCOPYDATA INTO @SOLICITANTE,@CONSECUTIVO,@AREA, @CARGO,@CENTRO_OPERACION,@FECHA_SOLICITUD, @CANTIDAD, @ITEM
	  WHILE @@FETCH_STATUS=0
	  
	  BEGIN

	   
		 	  SET @INID= ( SELECT DISTINCT  MIN(T.CONSECUTIVO)  FROM (SELECT MAX(REQUISICIONES.CNSREQ) AS CONSECUTIVO ,MAX(CONVERT(VARCHAR(16),ITEMSREQ.FECHA_SOLICITUD,20) )AS MAXFSA ,MAX(CONVERT(VARCHAR(16),REQUISICIONES.FECHA_SOLICITUD,20)) MAXFSAA1
              FROM REQUISICIONES  INNER JOIN ITEMSREQ ON ITEMSREQ.CEDULA = REQUISICIONES.CEDULA AND 
			  ITEMSREQ.CARGO = REQUISICIONES.CARGO   
              WHERE REQUISICIONES.REVISION IS NULL AND REQUISICIONES.APROBACION IS NULL
			  AND REQUISICIONES.FIRMA_REVISION IS NULL AND  REQUISICIONES.CNSREQ NOT IN 
              (SELECT CONSECUTIVO  FROM RQITEMSTEMPORAL) GROUP BY
	          REQUISICIONES.CNSREQ,  REQUISICIONES.FECHA_SOLICITUD,ITEMSREQ.FECHA_SOLICITUD
              HAVING CONVERT(VARCHAR(16),ITEMSREQ.FECHA_SOLICITUD,20) = CONVERT(VARCHAR(16),REQUISICIONES.FECHA_SOLICITUD,20) )  AS T

              INNER JOIN 

	         (SELECT MAX(REQUISICIONES.CNSREQ) AS CONSECUTIVO ,MAX(CONVERT(VARCHAR(16),ITEMSREQ.FECHA_SOLICITUD,20) ) AS MAXFSB,MAX(CONVERT(VARCHAR(16),REQUISICIONES.FECHA_SOLICITUD,20)) AS MAXFSAA2
              FROM REQUISICIONES  
			  INNER JOIN 
			  ITEMSREQ ON ITEMSREQ.CEDULA = REQUISICIONES.CEDULA AND ITEMSREQ.CARGO = REQUISICIONES.CARGO   
              WHERE REQUISICIONES.REVISION IS NULL AND REQUISICIONES.APROBACION IS NULL
			  AND REQUISICIONES.FIRMA_REVISION IS NULL AND  REQUISICIONES.CNSREQ NOT IN 
             (SELECT CONSECUTIVO  FROM RQITEMSTEMPORAL) 
			  GROUP BY
	          REQUISICIONES.CNSREQ,  REQUISICIONES.FECHA_SOLICITUD,ITEMSREQ.FECHA_SOLICITUD
              HAVING CONVERT(VARCHAR(16),ITEMSREQ.FECHA_SOLICITUD,20) = CONVERT(VARCHAR(16),REQUISICIONES.FECHA_SOLICITUD,20) ) AS H

              ON T.CONSECUTIVO = H.CONSECUTIVO)


              INSERT INTO RQITEMSTEMPORAL SELECT REQUISICIONES.SOLICITANTE AS SOLICITANTE, 
              REQUISICIONES.CNSREQ AS CONSECUTIVO, REQUISICIONES.AREA AS AREA, REQUISICIONES.CARGO AS CARGO,
			  REQUISICIONES.CENTRO_OPERACION AS CENTRO_OPERACION,
              REQUISICIONES.FECHA_SOLICITUD AS FECHA_SOLICITUD, CANTIDAD AS CANTIDAD, ITEM AS ITEM
              FROM REQUISICIONES  
			  INNER JOIN ITEMSREQ 
			  ON ITEMSREQ.CEDULA = REQUISICIONES.CEDULA AND ITEMSREQ.CARGO = REQUISICIONES.CARGO   
              WHERE REQUISICIONES.REVISION IS NULL AND REQUISICIONES.APROBACION IS NULL
			  AND REQUISICIONES.FIRMA_REVISION IS NULL AND  REQUISICIONES.CNSREQ NOT IN 
              (SELECT CONSECUTIVO  FROM RQITEMSTEMPORAL)  AND REQUISICIONES.CNSREQ=@INID  
			  GROUP BY
	          REQUISICIONES.CARGO,  REQUISICIONES.CEDULA, REQUISICIONES.CENTRO_OPERACION,  
              ITEMSREQ.CANTIDAD,  ITEMSREQ.ITEM , REQUISICIONES.CNSREQ, REQUISICIONES.SOLICITANTE, REQUISICIONES.FECHA_SOLICITUD, ITEMSREQ.FECHA_SOLICITUD,  REQUISICIONES.AREA  
              HAVING CONVERT(VARCHAR(16),ITEMSREQ.FECHA_SOLICITUD,20) = CONVERT(VARCHAR(16),REQUISICIONES.FECHA_SOLICITUD,20)



		   FETCH NEXT FROM INSERTFINALCOPYDATA INTO @SOLICITANTE,@CONSECUTIVO,@AREA, @CARGO,@CENTRO_OPERACION, @FECHA_SOLICITUD, @CANTIDAD, @ITEM
      END

CLOSE INSERTFINALCOPYDATA;  
DEALLOCATE INSERTFINALCOPYDATA

GO



exec INSERTAFINALDATACOPY