CREATE PROCEDURE ACTUALIZAF
AS
DECLARE @CNSINC VARCHAR(20),
        @CNSRINC VARCHAR(20), 
	    @FECHATEMP VARCHAR(20)

DECLARE FECHATEMP CURSOR

FOR

    SELECT  CNSINC, CNSRINC, CONVERT(VARCHAR(20),FECHA_SOLICITUD,105) 
    AS FECHA_SOLICITUD FROM INCIDENTES


    OPEN FECHATEMP FETCH NEXT FROM FECHATEMP INTO @CNSINC , @CNSRINC ,@FECHATEMP
    WHILE @@FETCH_STATUS=0
      
	  BEGIN

           UPDATE INCIDENTES SET INCIDENTES.FECHA_TEMPORAL_S=@FECHATEMP
           WHERE CNSINC=@CNSINC AND CNSRINC=@CNSRINC

    
           FETCH NEXT FROM FECHATEMP INTO @CNSINC , @CNSRINC ,@FECHATEMP
     END

CLOSE FECHATEMP ;
DEALLOCATE FECHATEMP

GO

