CREATE PROCEDURE VINCULAR

AS

 SELECT INCIDENTES.ID AS 'INCIDENTES ID', 
        RINCIDENTES.CNSRINC AS 'CONCECUTIVO RESPUESTA INCIDENTES',
	    RINCIDENTES.ID AS 'RINCIDENTES ID'
FROM INCIDENTES 
INNER JOIN RINCIDENTES
ON INCIDENTES.CNSINC= RINCIDENTES.CNSINC
			 
UPDATE INCIDENTES 
SET INCIDENTES.CNSRINC=RINCIDENTES.CNSRINC,  INCIDENTES.CNSRID=RINCIDENTES.ID 
FROM INCIDENTES 
INNER JOIN RINCIDENTES 
ON INCIDENTES.CNSINC= RINCIDENTES.CNSINC
 
UPDATE RINCIDENTES SET RINCIDENTES.CNSID=INCIDENTES.ID
FROM INCIDENTES INNER JOIN 
RINCIDENTES 
ON INCIDENTES.CNSRID=RINCIDENTES.ID
WHERE INCIDENTES.CNSRINC = RINCIDENTES.CNSRINC

GO