CREATE PROCEDURE DELETETABLEMARZO
AS
DROP TABLE IF EXISTS dbo.MARZO

CREATE TABLE MARZO
(
ID INT IDENTITY(1,1) NOT NULL,
CNSMAR AS RIGHT ('CNSMAR' + CAST (ID AS VARCHAR(20)),20) PERSISTED NOT NULL,
DIAMARZO VARCHAR(30) NULL,
CONSTRAINT PK_MARD PRIMARY KEY CLUSTERED(ID,CNSMAR)
)


GO

EXEC DELETETABLEMARZO