CREATE PROCEDURE DELETETABLEENERO
AS
DROP TABLE IF EXISTS dbo.ENERO

CREATE TABLE ENERO
(
ID INT IDENTITY(1,1) NOT NULL,
CNSJAN AS RIGHT ('CNSJAN' + CAST (ID AS VARCHAR(20)),20) PERSISTED NOT NULL,
DIAENERO VARCHAR(30) NULL,
CONSTRAINT PK_ENEROD PRIMARY KEY CLUSTERED(ID,CNSJAN)
)

GO

EXEC DELETETABLEENERO