CREATE TRIGGER DEPURACOPIA
ON RQITEMSTEMPORAL
FOR INSERT
        
AS
BEGIN

IF EXISTS(
          SELECT  REQUISICIONES.CNSREQ AS CONSECUTIVO FROM REQUISICIONES   
          INNER JOIN 
		  ITEMSREQ 
		  ON ITEMSREQ.CEDULA = REQUISICIONES.CEDULA AND ITEMSREQ.CARGO = REQUISICIONES.CARGO   
          WHERE REQUISICIONES.REVISION IS NULL AND REQUISICIONES.APROBACION IS NULL AND REQUISICIONES.FIRMA_REVISION IS NULL 
          AND  REQUISICIONES.CNSREQ NOT IN (SELECT RQITEMSTEMPORAL.CONSECUTIVO FROM RQITEMSTEMPORAL)	
		  GROUP BY  REQUISICIONES.CARGO, REQUISICIONES.CEDULA,  ITEMSREQ.CANTIDAD,    
	   	  ITEMSREQ.ITEM , REQUISICIONES.CNSREQ, REQUISICIONES.SOLICITANTE, REQUISICIONES.FECHA_SOLICITUD, ITEMSREQ.FECHA_SOLICITUD,  REQUISICIONES.AREA , REQUISICIONES.CENTRO_OPERACION 							 
	   	  HAVING CONVERT(VARCHAR(16),ITEMSREQ.FECHA_SOLICITUD,20) = CONVERT(VARCHAR(16),REQUISICIONES.FECHA_SOLICITUD,20) 
		  )  
		   							
	  ROLLBACK
      RAISERROR('NO SE PUEDEN INSERTAR DATOS DUPLICADOS',14,1);
      RETURN

END
GO

DISABLE TRIGGER   DEPURACOPIA ON RQITEMSTEMPORAL;
GO