SELECT  REQUISICIONES.SOLICITANTE AS SOLICITANTE, REQUISICIONES.CNSREQ AS CONSECUTIVO, REQUISICIONES.AREA AS AREA,  REQUISICIONES.CARGO AS CARGO,REQUISICIONES.FECHA_SOLICITUD  AS FECHA_SOLICITUD, ITEMSREQ.CANTIDAD AS CANTIDAD,  ITEMSREQ.ITEM AS ITEM  FROM REQUISICIONES
INNER JOIN ITEMSREQ ON ITEMSREQ.CEDULA = REQUISICIONES.CEDULA AND ITEMSREQ.CARGO = REQUISICIONES.CARGO
WHERE REQUISICIONES.REVISION IS NULL AND REQUISICIONES.APROBACION IS NULL AND REQUISICIONES.FIRMA_REVISION IS NULL 
AND 
CONVERT(DATE,ITEMSREQ.FECHA_SOLICITUD,103)>='2019/12/17' AND CONVERT(DATE,ITEMSREQ.FECHA_SOLICITUD,103) <='2019/12/17'
AND REQUISICIONES.CARGO = 'Coordinador De Sistemas' AND REQUISICIONES.AREA = 'Sistemas'
GROUP BY REQUISICIONES.CARGO, 
REQUISICIONES.CEDULA, 
ITEMSREQ.CANTIDAD, 
ITEMSREQ.ITEM ,
REQUISICIONES.CNSREQ,
REQUISICIONES.SOLICITANTE,
REQUISICIONES.FECHA_SOLICITUD,
ITEMSREQ.FECHA_SOLICITUD,
REQUISICIONES.AREA
HAVING CONVERT(VARCHAR(30),ITEMSREQ.FECHA_SOLICITUD,20) = CONVERT(VARCHAR(30),REQUISICIONES.FECHA_SOLICITUD,20)
ORDER BY 2 ASC


/* AND
CONVERT(VARCHAR(30),ITEMSREQ.FECHA_SOLICITUD,20)>='2019/12/17'*/

/*CONVERT(VARCHAR(30),REQUISICIONES.FECHA_SOLICITUD,20)*/







