SELECT  MIDATA.[CONSECUTIVO REQUISICION],MIDATA.SOLICITANTE, MIDATA.AREA, MIDATA.CARGO,MIDATA.[FECHA DE SOLICITUD], MIDATA.[FECHA DE APROBACION], MIDATA.[ITEM APROBADO] AS 'ITEMS APROBADOS', COALESCE(MIDATA.[ITEM NO APROBADO],0) AS 'ITEMS NO APROBADOS' FROM  (SELECT * FROM (SELECT 
REQUISICIONES.CNSREQ AS 'CONSECUTIVO REQUISICION', 
REQUISICIONES.SOLICITANTE AS 'SOLICITANTE',
REQUISICIONES.AREA AS 'AREA',
REQUISICIONES.CARGO AS 'CARGO', 
CONVERT(VARCHAR(16),REQUISICIONES.FECHA_SOLICITUD,20) AS 'FECHA DE SOLICITUD',
CONVERT(VARCHAR(16),REQUISICIONESDT.FECHA_DE_FIRMA,20) AS 'FECHA DE APROBACION',
COUNT(ITEMSREQ.ITEM) AS CANTIDAD,
(CASE WHEN ITEMSREQ.ITEMAPROBADO=1 THEN  'ITEM APROBADO'
      WHEN ITEMSREQ.ITEMAPROBADO=0 THEN 'ITEM NO APROBADO' END) AS ESTADO
FROM REQUISICIONES
	   INNER JOIN ITEMSREQ ON
	   ITEMSREQ.CNSREQ = REQUISICIONES.CNSREQ
	   INNER JOIN REQUISICIONESDT ON
	   REQUISICIONESDT.CNSREQ = REQUISICIONES.CNSREQ
	   WHERE REQUISICIONES.APROBACION=1 AND ITEMSREQ.ITEMAPROBADO = 1 AND  REQUISICIONES.APROBACION=1 OR ITEMSREQ.ITEMAPROBADO = 0
	   GROUP BY REQUISICIONES.CNSREQ,REQUISICIONES.SOLICITANTE,REQUISICIONES.CARGO,REQUISICIONES.FECHA_SOLICITUD,
	   REQUISICIONESDT.FECHA_DE_FIRMA,ITEMSREQ.ITEMAPROBADO,REQUISICIONES.AREA
	   ) AS T
	    PIVOT
	   (
	   SUM (CANTIDAD)  
       FOR ESTADO IN  
       (  [ITEM APROBADO],[ITEM NO APROBADO] )  
      )  AS PIVOTTABLE)MIDATA
	  WHERE CAST(MIDATA.[FECHA DE APROBACION] AS DATE)>='01/01/2019' AND CAST(MIDATA.[FECHA DE APROBACION] AS DATE)<='31/12/2020'
	  ORDER BY CONVERT(VARCHAR(16),MIDATA.[FECHA DE SOLICITUD],20) ASC

	  	  /*WHERE CONVERT(VARCHAR(30),MIDATA.[FECHA DE APROBACION],103)<='2019/12/12'*/



	  SELECT  REQUISICIONES.CNSREQ AS 'CONSECUTIVO REQUISICION',  REQUISICIONES.SOLICITANTE AS 'SOLICITANTE', REQUISICIONES.AREA AS 'AREA', REQUISICIONES.CARGO AS 'CARGO', CONVERT(VARCHAR(16),REQUISICIONES.FECHA_SOLICITUD,20) AS 'FECHA DE SOLICITUD', CONVERT(VARCHAR(16),REQUISICIONESDT.FECHA_DE_FIRMA,20) AS 'FECHA DE APROBACION', ITEMSREQ.ITEM AS 'ITEM',  ITEMSREQ.CANTIDAD AS 'CANTIDAD' , (CASE WHEN ITEMSREQ.ITEMAPROBADO=1 THEN 'ITEM APROBADO' WHEN ITEMSREQ.ITEMAPROBADO=0 THEN 'ITEM  NO APROBADO' END) AS 'ESTADO ITEM' FROM REQUISICIONES INNER JOIN ITEMSREQ ON ITEMSREQ.CNSREQ = REQUISICIONES.CNSREQ INNER JOIN REQUISICIONESDT ON REQUISICIONESDT.CNSREQ = REQUISICIONES.CNSREQ WHERE REQUISICIONES.APROBACION=1 AND ITEMSREQ.ITEMAPROBADO = 1