SELECT 
REQUISICIONES.CNSREQ AS 'CONSECUTIVO REQUISICION', 
REQUISICIONES.SOLICITANTE AS 'SOLICITANTE',
REQUISICIONES.CARGO AS 'CARGO', 
CONVERT(VARCHAR(16),REQUISICIONES.FECHA_SOLICITUD,20) AS 'FECHA DE SOLICITUD',
CONVERT(VARCHAR(16),REQUISICIONESDT.FECHA_DE_FIRMA,20) AS 'FECHA DE APROBACION',
ITEMSREQ.ITEM AS 'ITEM', 
ITEMSREQ.CANTIDAD AS 'CANTIDAD' ,
(CASE WHEN ITEMSREQ.ITEMAPROBADO=1 THEN 'ITEM APROBADO'
      WHEN ITEMSREQ.ITEMAPROBADO=0 THEN 'ITEM  NO APROBADO' END) AS 'ESTADO ITEM'

FROM REQUISICIONES
	   INNER JOIN ITEMSREQ ON
	   ITEMSREQ.CNSREQ = REQUISICIONES.CNSREQ
	   INNER JOIN REQUISICIONESDT ON
	   REQUISICIONESDT.CNSREQ = REQUISICIONES.CNSREQ
	   WHERE REQUISICIONES.APROBACION=1 AND ITEMSREQ.ITEMAPROBADO = 1

