SELECT COUNT(SOLICITUD) AS CANTIDAD, ISNULL(CONVERT(VARCHAR(50),MAX(FECHA_SOLICITUD),105),'00-00-1900') AS 'FECHA SOLICITUD' FROM INCIDENTES WHERE SOLICITUD='DAÑO DE EQUIPO'
SELECT COUNT(SOLICITUD) AS CANTIDAD, ISNULL(CONVERT(VARCHAR(50),MAX(FECHA_SOLICITUD),105),'00-00-1900') AS 'FECHA SOLICITUD' FROM INCIDENTES WHERE SOLICITUD='ERROR DE SOFTWARE'
SELECT COUNT(SOLICITUD) AS CANTIDAD, ISNULL(CONVERT(VARCHAR(50),MAX(FECHA_SOLICITUD),105),'00-00-1900') AS 'FECHA SOLICITUD' FROM INCIDENTES WHERE SOLICITUD='FALLA EN TELEFONO'
SELECT COUNT(SOLICITUD) AS CANTIDAD, ISNULL(CONVERT(VARCHAR(50),MAX(FECHA_SOLICITUD),105),'00-00-1900')AS 'FECHA SOLICITUD' FROM INCIDENTES WHERE SOLICITUD='MANTENIMIENTO CORRECTIVO'
SELECT COUNT(SOLICITUD) AS CANTIDAD, ISNULL(CONVERT(VARCHAR(50),MAX(FECHA_SOLICITUD),105),'00-00-1900') AS 'FECHA SOLICITUD' FROM INCIDENTES WHERE SOLICITUD='MANTENIMIENTO PREVENTIVO'
SELECT COUNT(SOLICITUD) AS CANTIDAD, ISNULL(CONVERT(VARCHAR(50),MAX(FECHA_SOLICITUD),105),'00-00-1900') AS 'FECHA SOLICITUD' FROM INCIDENTES WHERE SOLICITUD='PROBLEMA CON DRIVER DE PC'
SELECT COUNT(SOLICITUD) AS CANTIDAD, ISNULL(CONVERT(VARCHAR(50),MAX(FECHA_SOLICITUD),105),'00-00-1900') AS 'FECHA SOLICITUD' FROM INCIDENTES WHERE SOLICITUD='PROBLEMA CON WIFI'
SELECT COUNT(SOLICITUD) AS CANTIDAD, ISNULL(CONVERT(VARCHAR(50),MAX(FECHA_SOLICITUD),105),'00-00-1900') AS 'FECHA SOLICITUD' FROM INCIDENTES WHERE SOLICITUD='EQUIPO LENTO'
SELECT COUNT(SOLICITUD) AS CANTIDAD, ISNULL(CONVERT(VARCHAR(50),MAX(FECHA_SOLICITUD),105),'00-00-1900') AS 'FECHA SOLICITUD' FROM INCIDENTES WHERE SOLICITUD='CONFIGURACION DE EQUIPO' 

GO


SELECT COUNT(SOLICITUD) AS CANTIDAD, 
ISNULL(CONVERT(VARCHAR(50),MAX(FECHA_SOLICITUD),105),'00-00-1900') AS 'FECHA SOLICITUD', CNSINC
FROM INCIDENTES 
WHERE SOLICITUD='CONFIGURACION DE EQUIPO' AND ISNULL(CONVERT(VARCHAR,FECHA_SOLICITUD,105),'00-00-1900')>='01/10/2019' AND ISNULL(CONVERT(VARCHAR,FECHA_SOLICITUD,105),'00-00-1900') <='31/10/2019'
GROUP BY FECHA_SOLICITUD, CNSINC

GO


SELECT COUNT(SOLICITUD) AS CANTIDAD,
ISNULL(CONVERT(VARCHAR(50),FECHA_SOLICITUD,105),'00-00-1900') AS 'FECHA SOLICITUD'
FROM INCIDENTES 
WHERE SOLICITUD='DAÑO DE EQUIPO' AND ISNULL(CONVERT(VARCHAR,FECHA_SOLICITUD,105),'00-00-1900')>='01-10-2019' AND ISNULL(CONVERT(VARCHAR,FECHA_SOLICITUD,105),'00-00-1900') <='31-10-2019'
GROUP BY FECHA_SOLICITUD

GO




SELECT COUNT(SOLICITUD) AS CANTIDAD,SOLICITUD,
ISNULL(CONVERT(VARCHAR(50),MAX(FECHA_SOLICITUD),105),'00-00-1900') AS 'FECHA SOLICITUD',CNSINC
FROM INCIDENTES 
WHERE SOLICITUD='EQUIPO LENTO' AND ISNULL(CONVERT(VARCHAR,FECHA_SOLICITUD,105),'00-00-1900')>='01/10/2019' AND ISNULL(CONVERT(VARCHAR,FECHA_SOLICITUD,105),'00-00-1900') <='31/11/2019'
GROUP BY FECHA_SOLICITUD,CNSINC,SOLICITUD


GO




SELECT COUNT(SOLICITUD) AS CANTIDAD, 
ISNULL(CONVERT(VARCHAR(50),MAX(FECHA_SOLICITUD),105),'00-00-1900') AS 'FECHA SOLICITUD'
FROM INCIDENTES 
WHERE SOLICITUD='PROBLEMA CON IMPRESORA' AND ISNULL(CONVERT(VARCHAR,FECHA_SOLICITUD,105),'00-00-1900')>='01/10/2019' AND ISNULL(CONVERT(VARCHAR,FECHA_SOLICITUD,105),'00-00-1900') <='31/11/2019'
GROUP BY FECHA_SOLICITUD, CNSINC

GO

SELECT COUNT(SOLICITUD) AS CANTIDAD, 
ISNULL(CONVERT(VARCHAR(50),MAX(FECHA_SOLICITUD),105),'00-00-1900') AS 'FECHA SOLICITUD',CNSINC
FROM INCIDENTES 
WHERE SOLICITUD='ERROR DE SOFTWARE' AND ISNULL(CONVERT(VARCHAR,FECHA_SOLICITUD,105),'00-00-1900')>='01/10/2019' AND ISNULL(CONVERT(VARCHAR,FECHA_SOLICITUD,105),'00-00-1900') <='31/11/2019'
GROUP BY FECHA_SOLICITUD,CNSINC

GO

SELECT COUNT(SOLICITUD) AS CANTIDAD, 
ISNULL(CONVERT(VARCHAR(50),MAX(FECHA_SOLICITUD),105),'00-00-1900') AS 'FECHA SOLICITUD',CNSINC
FROM INCIDENTES 
WHERE SOLICITUD='MANTENIMIENTO CORRECTIVO' AND ISNULL(CONVERT(VARCHAR,FECHA_SOLICITUD,105),'00-00-1900')>='01/10/2019' AND ISNULL(CONVERT(VARCHAR,FECHA_SOLICITUD,105),'00-00-1900') <='31/11/2019'
GROUP BY FECHA_SOLICITUD,CNSINC

GO

SELECT COUNT(SOLICITUD) AS CANTIDAD, 
ISNULL(CONVERT(VARCHAR(50),MAX(FECHA_SOLICITUD),105),'00-00-1900') AS 'FECHA SOLICITUD',CNSINC
FROM INCIDENTES 
WHERE SOLICITUD='MANTENIMIENTO PREVENTIVO' AND ISNULL(CONVERT(VARCHAR,FECHA_SOLICITUD,105),'00-00-1900')>='01/10/2019' AND ISNULL(CONVERT(VARCHAR,FECHA_SOLICITUD,105),'00-00-1900') <='31/11/2019'
GROUP BY FECHA_SOLICITUD,CNSINC

GO

SELECT COUNT(SOLICITUD) AS CANTIDAD, 
ISNULL(CONVERT(VARCHAR(50),MAX(FECHA_SOLICITUD),105),'00-00-1900') AS 'FECHA SOLICITUD',CNSINC
FROM INCIDENTES 
WHERE SOLICITUD='FALLA EN EL TELEFONO' AND ISNULL(CONVERT(VARCHAR,FECHA_SOLICITUD,105),'00-00-1900')>='01/10/2019' AND ISNULL(CONVERT(VARCHAR,FECHA_SOLICITUD,105),'00-00-1900') <='31/11/2019'
GROUP BY FECHA_SOLICITUD,CNSINC

GO

SELECT COUNT(SOLICITUD) AS CANTIDAD, 
ISNULL(CONVERT(VARCHAR(50),MAX(FECHA_SOLICITUD),105),'00-00-1900') AS 'FECHA SOLICITUD',CNSINC
FROM INCIDENTES 
WHERE SOLICITUD='PROBLEMA CON DRIVER DE PC' AND ISNULL(CONVERT(VARCHAR,FECHA_SOLICITUD,105),'00-00-1900')>='01/10/2019' AND ISNULL(CONVERT(VARCHAR,FECHA_SOLICITUD,105),'00-00-1900') <='31/11/2019'
GROUP BY FECHA_SOLICITUD,CNSINC

GO

SELECT COUNT(SOLICITUD) AS CANTIDAD, 
ISNULL(CONVERT(VARCHAR(50),MAX(FECHA_SOLICITUD),105),'00-00-1900') AS 'FECHA SOLICITUD',CNSINC
FROM INCIDENTES 
WHERE SOLICITUD='PROBLEMA CON WIFI' AND ISNULL(CONVERT(VARCHAR,FECHA_SOLICITUD,105),'00-00-1900')>='01/10/2019' AND ISNULL(CONVERT(VARCHAR,FECHA_SOLICITUD,105),'00-00-1900') <='31/11/2019'
GROUP BY FECHA_SOLICITUD,CNSINC


GO



SELECT(CASE WHEN SOLICITUD='PROBLEMA CON IMPRESORA' THEN COUNT(SOLICITUD) 
             WHEN SOLICITUD='DAÑO DE EQUIPO' THEN COUNT(SOLICITUD)
			 WHEN SOLICITUD='ERROR DE SOFTWARE' THEN COUNT(SOLICITUD)
			 WHEN SOLICITUD='MANTENIMIENTO CORRECTIVO' THEN COUNT(SOLICITUD)
			 WHEN SOLICITUD='MANTENIMIENTO PREVENTIVO' THEN COUNT(SOLICITUD)
			 WHEN SOLICITUD='FALLA EN TELEFONO' THEN COUNT(SOLICITUD)
			 WHEN SOLICITUD='PROBLEMA CON DRIVER DE PC' THEN COUNT(SOLICITUD)
			 WHEN SOLICITUD='PROBLEMA CON WIFI' THEN COUNT(SOLICITUD)
			 WHEN SOLICITUD='CONFIGURACION DE EQUIPO' THEN COUNT(SOLICITUD)
			 WHEN SOLICITUD='EQUIPO LENTO' THEN COUNT(SOLICITUD)
END) AS CONTEO, ISNULL(CONVERT(VARCHAR(50),MAX(FECHA_SOLICITUD),105),'00-00-1900') AS 'FECHA SOLICITUD' FROM INCIDENTES
WHERE ISNULL(CONVERT(VARCHAR,FECHA_SOLICITUD,105),'00-00-1900')>='01/10/2019' AND ISNULL(CONVERT(VARCHAR,FECHA_SOLICITUD,105),'00-00-1900') <='31/11/2019'
GROUP BY SOLICITUD


GO



SELECT(CASE WHEN SOLICITUD='PROBLEMA CON IMPRESORA' THEN COUNT(SOLICITUD) 
             WHEN SOLICITUD='DAÑO DE EQUIPO' THEN COUNT(SOLICITUD)
			 WHEN SOLICITUD='ERROR DE SOFTWARE' THEN COUNT(SOLICITUD)
			 WHEN SOLICITUD='MANTENIMIENTO CORRECTIVO' THEN COUNT(SOLICITUD)
			 WHEN SOLICITUD='MANTENIMIENTO PREVENTIVO' THEN COUNT(SOLICITUD)
			 WHEN SOLICITUD='FALLA EN TELEFONO' THEN COUNT(SOLICITUD)
			 WHEN SOLICITUD='PROBLEMA CON DRIVER DE PC' THEN COUNT(SOLICITUD)
			 WHEN SOLICITUD='PROBLEMA CON WIFI' THEN COUNT(SOLICITUD)
			 WHEN SOLICITUD='CONFIGURACION DE EQUIPO' THEN COUNT(SOLICITUD)
			 WHEN SOLICITUD='EQUIPO LENTO' THEN COUNT(SOLICITUD)
END) AS CONTEO, MAX(CONVERT(VARCHAR(50),FECHA_SOLICITUD,105)) AS 'FECHA SOLICITUD', SOLICITUD FROM INCIDENTES
GROUP BY SOLICITUD

GO