------------------------A----------------------------

	  DECLARE @CNSREQ VARCHAR(30)
	  DECLARE @ID INT
	  DECLARE @CNSRQDT VARCHAR(30)
	  DECLARE @ID2 INT
	  DECLARE @IDCNSREQ INT
	  DECLARE @FINALCNSREQ VARCHAR(30)
	  DECLARE @FINALCNSRQDT VARCHAR(30)
	  DECLARE @IDCNSRQDT INT
      
	 

	  SET @CNSREQ=(SELECT MIN(REQUISICIONESDT.CNSREQ) FROM REQUISICIONESDT
	      INNER JOIN 
	          REQUISICIONES
		        ON REQUISICIONESDT.CNSRQDT = REQUISICIONES.CNSRQDT AND REQUISICIONES.IDRQDT = REQUISICIONESDT.ID
		   AND REQUISICIONES.CNSREQ = REQUISICIONESDT.CNSREQ AND REQUISICIONESDT.IDREQ = REQUISICIONES.ID
	    WHERE REQUISICIONES.CNSRQDT = REQUISICIONES.CNSRQDT AND REQUISICIONES.IDRQDT = REQUISICIONESDT.ID)

	  SELECT REQUISICIONES.CNSREQ, REQUISICIONES.ID, REQUISICIONES.CNSRQDT FROM REQUISICIONES
	   INNER JOIN 
	      REQUISICIONESDT
		      ON REQUISICIONESDT.CNSRQDT = REQUISICIONES.CNSRQDT AND REQUISICIONES.IDRQDT = REQUISICIONESDT.ID
			   AND REQUISICIONES.CNSREQ = REQUISICIONESDT.CNSREQ AND REQUISICIONESDT.IDREQ = REQUISICIONES.ID
		WHERE REQUISICIONES.CNSRQDT = REQUISICIONES.CNSRQDT AND REQUISICIONES.IDRQDT = REQUISICIONESDT.ID
	AND REQUISICIONES.CNSREQ = @CNSREQ

	    UPDATE REQUISICIONESDT SET  REQUISICIONESDT.CNSREQ=NULL, REQUISICIONESDT.IDREQ=NULL
		  FROM REQUISICIONES INNER JOIN REQUISICIONESDT
			 ON REQUISICIONESDT.CNSRQDT = REQUISICIONES.CNSRQDT AND REQUISICIONES.IDRQDT = REQUISICIONESDT.ID
	   WHERE REQUISICIONES.CNSRQDT = REQUISICIONES.CNSRQDT AND REQUISICIONES.IDRQDT = REQUISICIONESDT.ID
      AND REQUISICIONES.CNSREQ = @CNSREQ

	    UPDATE REQUISICIONES SET REQUISICIONES.CNSRQDT=NULL, REQUISICIONES.IDRQDT=NULL
	      FROM REQUISICIONES INNER JOIN REQUISICIONESDT
		  ON REQUISICIONESDT.CNSRQDT = REQUISICIONES.CNSRQDT AND REQUISICIONES.IDRQDT = REQUISICIONESDT.ID
       WHERE REQUISICIONES.CNSRQDT = REQUISICIONES.CNSRQDT AND REQUISICIONES.IDRQDT = REQUISICIONESDT.ID
     AND REQUISICIONES.CNSREQ = @CNSREQ

	   SET @ID2=(SELECT MIN(REQUISICIONESDT.ID) FROM REQUISICIONESDT
	    WHERE ISNULL(REQUISICIONESDT.IDREQ,0)<>0)
     DELETE FROM REQUISICIONESDT WHERE REQUISICIONESDT.ID=@ID2

	 
	  SET @IDCNSREQ=(SELECT MIN (REQUISICIONES.ID)FROM REQUISICIONES
	      INNER JOIN REQUISICIONESDT ON
	    REQUISICIONESDT.CEDULA = REQUISICIONES.CEDULA AND REQUISICIONES.FECHA_SOLICITUD = REQUISICIONESDT.FECHA_SOLICITUD
		 WHERE REQUISICIONES.CNSRQDT IS NULL AND REQUISICIONES.IDRQDT IS NULL)

		SET @FINALCNSREQ=(SELECT MIN (REQUISICIONES.CNSREQ)FROM REQUISICIONES
			INNER JOIN REQUISICIONESDT ON
		REQUISICIONESDT.CEDULA = REQUISICIONES.CEDULA AND REQUISICIONES.FECHA_SOLICITUD = REQUISICIONESDT.FECHA_SOLICITUD
		 WHERE REQUISICIONES.CNSRQDT IS NULL AND REQUISICIONES.IDRQDT IS NULL)

         SET @FINALCNSRQDT=(SELECT MIN(REQUISICIONESDT.CNSRQDT) FROM REQUISICIONES
		   INNER JOIN REQUISICIONESDT ON
		  REQUISICIONESDT.CEDULA = REQUISICIONES.CEDULA AND REQUISICIONES.FECHA_SOLICITUD = REQUISICIONESDT.FECHA_SOLICITUD
		   WHERE REQUISICIONES.CNSRQDT IS NULL AND REQUISICIONES.IDRQDT IS NULL)
					      
          SET @IDCNSRQDT=(SELECT MIN (REQUISICIONESDT.ID)FROM REQUISICIONES
		   INNER JOIN REQUISICIONESDT ON
		 REQUISICIONESDT.CEDULA = REQUISICIONES.CEDULA AND REQUISICIONES.FECHA_SOLICITUD = REQUISICIONESDT.FECHA_SOLICITUD  
		 WHERE REQUISICIONES.CNSRQDT IS NULL AND REQUISICIONES.IDRQDT IS NULL)
					      
           UPDATE REQUISICIONES SET REQUISICIONES.CNSRQDT = @FINALCNSRQDT, REQUISICIONES.IDRQDT=@IDCNSRQDT FROM REQUISICIONES
		    INNER JOIN REQUISICIONESDT ON
		     REQUISICIONESDT.CEDULA = REQUISICIONES.CEDULA AND REQUISICIONES.FECHA_SOLICITUD = REQUISICIONESDT.FECHA_SOLICITUD
		    WHERE REQUISICIONESDT.CNSRQDT = @FINALCNSRQDT AND REQUISICIONESDT.ID = @IDCNSRQDT 


-------------------------------FIN A------------------------------------------

  		   

--------------------------B-------------------------------------------------------
	 DECLARE @UPDATECNSREQ VARCHAR(30)
	  DECLARE @UPDATEIDCNSREQ INT	
	  DECLARE @UPDATECNSRQDT VARCHAR(30)


	    SELECT MIN(REQUISICIONES.CNSREQ), MIN(REQUISICIONES.ID), MIN(REQUISICIONESDT.CNSRQDT), MIN(REQUISICIONESDT.ID) FROM REQUISICIONES
			   INNER JOIN REQUISICIONESDT ON
			   REQUISICIONES.CNSRQDT = REQUISICIONESDT.CNSRQDT
			   WHERE REQUISICIONESDT.CNSREQ IS NULL AND REQUISICIONESDT.IDREQ IS NULL
			  HAVING MIN( REQUISICIONESDT.CNSRQDT) = MIN( REQUISICIONES.CNSRQDT )

			SET @UPDATECNSREQ =(SELECT MIN(REQUISICIONES.CNSREQ)  FROM REQUISICIONES
			   INNER JOIN REQUISICIONESDT ON
			   REQUISICIONES.CNSRQDT = REQUISICIONESDT.CNSRQDT
			   WHERE REQUISICIONESDT.CNSREQ IS NULL AND REQUISICIONESDT.IDREQ IS NULL
			  HAVING MIN( REQUISICIONESDT.CNSRQDT) = MIN( REQUISICIONES.CNSRQDT ))
					
				SET @UPDATEIDCNSREQ =(SELECT  MIN (REQUISICIONES.ID) FROM REQUISICIONES
				 INNER JOIN REQUISICIONESDT ON
				 REQUISICIONES.CNSRQDT = REQUISICIONESDT.CNSRQDT
				  WHERE REQUISICIONESDT.CNSREQ IS NULL AND REQUISICIONESDT.IDREQ IS NULL
				 HAVING MIN( REQUISICIONESDT.CNSRQDT) = MIN( REQUISICIONES.CNSRQDT ))
	        
				SET @UPDATECNSRQDT =(SELECT  MIN(REQUISICIONESDT.CNSRQDT)  FROM REQUISICIONES
				  INNER JOIN REQUISICIONESDT ON
				  REQUISICIONES.CNSRQDT = REQUISICIONESDT.CNSRQDT
				 WHERE REQUISICIONESDT.CNSREQ IS NULL AND REQUISICIONESDT.IDREQ IS NULL
				 HAVING MIN( REQUISICIONESDT.CNSRQDT) = MIN( REQUISICIONES.CNSRQDT ))

	            UPDATE  REQUISICIONESDT SET  REQUISICIONESDT.CNSREQ =@UPDATECNSREQ,  REQUISICIONESDT.IDREQ=@UPDATEIDCNSREQ
				    FROM REQUISICIONESDT INNER JOIN REQUISICIONES
					 ON  REQUISICIONES.CNSRQDT = REQUISICIONESDT.CNSRQDT AND REQUISICIONESDT.ID = REQUISICIONES.IDRQDT
					 WHERE REQUISICIONESDT.CNSRQDT = @UPDATECNSRQDT 
					
			
------------------------------------FIN B---------------------------------------------------------


			SELECT REQUISICIONES.ID,REQUISICIONES.CNSREQ, REQUISICIONESDT.CNSRQDT, REQUISICIONESDT.ID FROM REQUISICIONES
					      INNER JOIN REQUISICIONESDT ON
						REQUISICIONESDT.CEDULA = REQUISICIONES.CEDULA AND REQUISICIONES.FECHA_SOLICITUD = REQUISICIONESDT.FECHA_SOLICITUD
					      

						

	    SELECT * FROM REQUISICIONESDT
					    SELECT * FROM REQUISICIONES


			